version: "3.7"

networks:
  backend-network:
    driver: bridge

  web:
    external:
      name: web

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_prod
    container_name: mitwirken_api_backend
    volumes:
      - ./backend:/app
    #command: sh -c "cd ./backend && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    networks:
      - backend-network
    ports:
      - "8800:8000"

  frontened:
    build:
      context: ./forntend
      dockerfile: Dockerfile_prod
    container_name: mitwirken_frontend
    volumes:
      - react_build:/app/build
    networks:
      - backend-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    expose:
      - 80

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react

    depends_on:
      - backend
      - frontened

    networks:
      - backend-network
      - web

    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-mitwirken.entrypoints=http
      - traefik.http.routers.web-radverkehr.rule=Host(`mitwirken.eu`)
      - traefik.http.routers.web-radverkehr.middlewares=https-redirect@file

      - traefik.http.routers.web-radverkehr-sec.entrypoints=https
      - traefik.http.routers.web-radverkehr-sec.entrypoints=Host(`mitwirken.eu`)

      - traefik.http.routers.web-radverkehr-sec.tls=true
      - traefik.http.routers.web-radverkehr-sec.tls.certresolver=le


volumes:
  react_build:
